In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

import pickle
import json

In [2]:
df = pd.read_csv("medical_insurance.csv")
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [4]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
df["age"]

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [6]:
df["sex"]

0       female
1         male
2         male
3         male
4         male
         ...  
1333      male
1334    female
1335    female
1336    female
1337    female
Name: sex, Length: 1338, dtype: object

In [7]:
df["sex"].value_counts()

male      676
female    662
Name: sex, dtype: int64

In [8]:
df["sex"].replace({"female":0,"male":1},inplace= True)

In [9]:
df["bmi"]

0       27.900
1       33.770
2       33.000
3       22.705
4       28.880
         ...  
1333    30.970
1334    31.920
1335    36.850
1336    25.800
1337    29.070
Name: bmi, Length: 1338, dtype: float64

In [10]:
df["smoker"].replace({"no":0,"yes":1},inplace = True)

In [11]:
df["children"]

0       0
1       1
2       3
3       0
4       0
       ..
1333    3
1334    0
1335    0
1336    0
1337    0
Name: children, Length: 1338, dtype: int64

In [12]:
df["children"].value_counts()

0    574
1    324
2    240
3    157
4     25
5     18
Name: children, dtype: int64

In [13]:
df["region"]

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...    
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1338, dtype: object

In [14]:
df["region"].value_counts()

southeast    364
southwest    325
northwest    325
northeast    324
Name: region, dtype: int64

In [15]:
df = pd.get_dummies(df , columns = ["region"])
df

age  sex     bmi  children  smoker      charges  region_northeast  \
0      19    0  27.900         0       1  16884.92400                 0   
1      18    1  33.770         1       0   1725.55230                 0   
2      28    1  33.000         3       0   4449.46200                 0   
3      33    1  22.705         0       0  21984.47061                 0   
4      32    1  28.880         0       0   3866.85520                 0   
...   ...  ...     ...       ...     ...          ...               ...   
1333   50    1  30.970         3       0  10600.54830                 0   
1334   18    0  31.920         0       0   2205.98080                 1   
1335   18    0  36.850         0       0   1629.83350                 0   
1336   21    0  25.800         0       0   2007.94500                 0   
1337   61    0  29.070         0       1  29141.36030                 0   

      region_northwest  region_southeast  region_southwest  
0                    0                 0                 1  
1                    0                 1                 0  
2                    0                 1                 0  
3                    1                 0                 0  
4                    1                 0                 0  
...                ...               ...               ...  
1333                 1                 0                 0  
1334                 0                 0                 0  
1335                 0                 1                 0  
1336                 0                 0                 1  
1337                 1                 0                 0  

[1338 rows x 10 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               1338 non-null   int64  
 1   sex               1338 non-null   int64  
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64  
 4   smoker            1338 non-null   int64  
 5   charges           1338 non-null   float64
 6   region_northeast  1338 non-null   uint8  
 7   region_northwest  1338 non-null   uint8  
 8   region_southeast  1338 non-null   uint8  
 9   region_southwest  1338 non-null   uint8  
dtypes: float64(2), int64(4), uint8(4)
memory usage: 68.1 KB


In [17]:
x = df.drop("charges", axis = 1)
y = df["charges"]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [18]:
x_train

age  sex     bmi  children  smoker  region_northeast  region_northwest  \
882    21    0  22.135         0       0                 1                 0   
505    37    1  30.875         3       0                 0                 1   
798    58    0  33.100         0       0                 0                 0   
792    22    0  23.180         0       0                 1                 0   
201    48    0  32.230         1       0                 0                 0   
...   ...  ...     ...       ...     ...               ...               ...   
466    60    0  28.700         1       0                 0                 0   
299    48    0  28.880         1       0                 0                 1   
493    61    1  43.400         0       0                 0                 0   
527    51    0  25.800         1       0                 0                 0   
1192   58    0  32.395         1       0                 1                 0   

      region_southeast  region_southwest  
882                  0                 0  
505                  0                 0  
798                  0                 1  
792                  0                 0  
201                  1                 0  
...                ...               ...  
466                  0                 1  
299                  0                 0  
493                  0                 1  
527                  0                 1  
1192                 0                 0  

[1070 rows x 9 columns]

In [19]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [20]:
# testing data evaluation

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test , y_pred)
print("MSE:",mse)

rmse = np.sqrt(mse)
print("RMSE:", rmse)

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

r2_value = r2_score(y_test, y_pred)
print("R-Squared:", r2_value)

MSE: 38304871.34868592
RMSE: 6189.092934242135
MAE: 4279.860834219363
R-Squared: 0.7449415564623687


In [21]:
# training data evaluation 

y_pred_train = model.predict(x_train)

mse = mean_squared_error(y_train , y_pred_train)
print("MSE:",mse)

rmse = np.sqrt(mse)
print("RMSE:", rmse)

mae = mean_absolute_error(y_train, y_pred_train)
print("MAE:", mae)

r2_value = r2_score(y_train, y_pred_train)
print("R-Squared:", r2_value)

MSE: 36100283.869831294
RMSE: 6008.351177305742
MAE: 4138.842762471062
R-Squared: 0.7520187377309014


In [22]:
x.head(1).T

0
age               19.0
sex                0.0
bmi               27.9
children           0.0
smoker             1.0
region_northeast   0.0
region_northwest   0.0
region_southeast   0.0
region_southwest   1.0

In [23]:
age = 27
sex = "female"
bmi = 21
children = 0
smoker = "no"
region = "southeast"

#charges = ?

In [24]:
test_array = np.array([age,0.0,bmi,children,0.0,0.0,0.1,0.0,0.0], ndmin = 2)

In [25]:
model.predict(test_array)

C:\Users\rupal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1500.24193803])

In [26]:
print(x.columns)
len(x.columns)

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')


9

In [27]:
x.shape[1]

9

In [28]:
project_data = {"sex":{"female":0,"male":1},
               "smoker":{"no":0,"yes":1},
               "columns":list(x.columns)}
project_data

{'sex': {'female': 0, 'male': 1},
 'smoker': {'no': 0, 'yes': 1},
 'columns': ['age',
  'sex',
  'bmi',
  'children',
  'smoker',
  'region_northeast',
  'region_northwest',
  'region_southeast',
  'region_southwest']}

In [29]:
columns_names = x.columns
columns_names

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [30]:
list(columns_names).index("region_southeast")

7

In [31]:
new_region = "region_" + region 
region_index = np.where(columns_names == new_region)
region_index

(array([7], dtype=int64),)

In [32]:
new_region = "region_" + region 
region_index = np.where(columns_names == new_region)[0][0]
region_index

7

In [33]:
test_array = np.zeros(x.shape[1])
test_array[0] = age
test_array[1] = project_data["sex"][sex]
test_array[2] = bmi
test_array[3] = children
test_array[4] = project_data["smoker"][smoker]
test_array[region_index] = 1
test_array

array([27.,  0., 21.,  0.,  0.,  0.,  0.,  1.,  0.])

In [34]:
result = np.around(model.predict([test_array])[0],2)
print(f"Medical Insurance Charges are : RS.{result}")

Medical Insurance Charges are : RS.1228.63


C:\Users\rupal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [35]:
test_array

array([27.,  0., 21.,  0.,  0.,  0.,  0.,  1.,  0.])

In [36]:
with open("Linear_Model.pkl","wb") as f:
    pickle.dump(model,f)

In [37]:
with open("Project_data.json","w") as f:
    json.dump(project_data,f)